### ISSUE TITLE
Implement JSON protocol

### ISSUE THREAD

**Issue by 5HT** [synrc/n2o#129]
for receiving real JSON sent from client with

```javascript
    ws.send({a:1,b:2});
```

**Comment by zzet** [comment]
@5HT mb you can add n2o_text protocol here: https://github.com/5HT/n2o/blob/master/src/endpoints/n2o_websocket.erl#L11 ?

**Comment by 5HT** [comment]
@zzet you can redefine protocol stack in `sys.config`

**Comment by 5HT** [comment]
JSON formatter implemented and JSON transport format defined:
```
  ws.send(enc({t:108,v:"maxim"}));
```

**Comment by zzet** [comment]
:+1:

**Comment by 5HT** [comment]
You can read more about it http://synrc.com/apps/n2o/doc/web/protocols.htm#sec8
