### ISSUE TITLE
Sample app created with mad is broken again

### ISSUE THREAD

**Issue by yashrk** [synrc/n2o#231]
How to reproduce:
```
wget https://github.com/synrc/mad/raw/master/mad
chmod +x mad
./mad app "sample"
cd sample
../mad deps compile plan bundle "web_app"
./web_app
```

Error log:
```
=ERROR REPORT==== 6-Sep-2015::18:51:06 ===
Error in process <0.163.0> with exit value:
{[{reason,undef},
  {mfa,{n2o_dynalo,init,3}},
  {stacktrace,
      [{n2o_dynalo,init,
           [{tcp,http},
            {http_req,#Port<0.24088>,ranch_tcp,keepalive,<0.163.0>,<<"GET">>,
                'HTTP/1.1',
                {{127,0,0,1},35677},
                <<"localhost">>,undefined,8001,<<"/n2o/utf8.js">>,
                [<<"utf8.js">>],
                <<>>,undefined,[],
                [{<<"host">>,<<"localhost:8001">>},
                 {<<"user-agent">>,
                  <<"Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0">>},
                 {<<"accept">>,<<"*/*">>},
                 {<<"accept-language">>,
                  <<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>},
                 {<<"accept-encoding">>,<<"gzip, deflate">>},
                 {<<"referer">>,<<"http://localhost:8001/">>},
                 {<<"cookie">>,
                  <<"site-sid=5209daee8b9f896b6113252a16a18968; blog_user_id=blog_user-1; session_id=; org.cups.sid=d6f343460d6d36514eddd6d79f92e0b5; user_id=">>},
                 {<<"connection">>,<<"keep-alive">>},
                 {<<"cache-control">>,<<"max-age=0">>}],
                [{<<"connection">>,[<<"keep-alive">>]}],
                undefined,[],waiting,<<>>,undefined,false,waiting,[],<<>>,
                undefined},
            {dir,"deps/n2o/priv",[{mimetypes,cow_mimetypes,all}]}],
           []},
       {cowboy_handler,handler_init,4,
           [{file,
                "/home/uri/mnt/yandex/src/education/web/n2o/sample/deps/cowboy/src/cowboy_handler.erl"},
            {line,64}]},
       {cowboy_protocol,execute,4,
           [{file,
                "/home/uri/mnt/yandex/src/education/web/n2o/sample/deps/cowboy/src/cowboy_protocol.erl"},
            {line,442}]}]},
  {req,
      [{socket,#Port<0.24088>},
       {transport,ranch_tcp},
       {connection,keepalive},
       {pid,<0.163.0>},
       {method,<<"GET">>},
       {version,'HTTP/1.1'},
       {peer,{{127,0,0,1},35677}},
       {host,<<"localhost">>},
       {host_info,undefined},
       {port,8001},
       {path,<<"/n2o/utf8.js">>},
       {path_info,[<<"utf8.js">>]},
       {qs,<<>>},
       {qs_vals,undefined},
       {bindings,[]},
       {headers,
           [{<<"host">>,<<"localhost:8001">>},
            {<<"user-agent">>,
             <<"Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0">>},
            {<<"accept">>,<<"*/*">>},
            {<<"accept-language">>,<<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>},
            {<<"accept-encoding">>,<<"gzip, deflate">>},
            {<<"referer">>,<<"http://localhost:8001/">>},
            {<<"cookie">>,
             <<"site-sid=5209daee8b9f896b6113252a16a18968; blog_user_id=blog_user-1; session_id=; org.cups.sid=d6f343460d6d36514eddd6d79f92e0b5; user_id=">>},
            {<<"connection">>,<<"keep-alive">>},
            {<<"cache-control">>,<<"max-age=0">>}]},
       {p_headers,[{<<"connection">>,[<<"keep-alive">>]}]},
       {cookies,undefined},
       {meta,[]},
       {body_state,waiting},
       {buffer,<<>>},
       {multipart,undefined},
       {resp_compress,false},
       {resp_state,waiting},
       {resp_headers,[]},
       {resp_body,<<>>},
       {onresponse,undefined}]},
  {opts,{dir,"deps/n2o/priv",[{mimetypes,cow_mimetypes,all}]}}],
 [{cowboy_protocol,execute,4,
      [{file,
           "/home/uri/mnt/yandex/src/education/web/n2o/sample/deps/cowboy/src/cowboy_protocol.erl"},
       {line,442}]}]}
...
```

Tested with Erlang/OTP 17 and 18 on Alt Linux and Ubuntu.

**Comment by 5HT** [comment]
We know it. We working on 2.9. We changed the name `n2o_dynalo` to `n2o_static`.
I will notify you in this thread to retry when finish.

**Comment by yashrk** [comment]
Thank you!

About issue posting policy — I have described an issue on IRC channel and haven't seen any reaction. Is GitHub chat more active now?

**Comment by 5HT** [comment]
https://gitter.im/synrc/n2o has 77 users.

**Comment by 5HT** [comment]
Unfortunately you created an Issue not in appropriate project.
Here you issue closed https://github.com/synrc/mad/issues/41.

**Comment by bhanuc** [comment]
I am trying to run the sample app but I get the following error:
 bhanuc_1:~/workspace $ git clone git://github.com/synrc/n2o
Cloning into 'n2o'...
remote: Counting objects: 10071, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 10071 (delta 1), reused 0 (delta 0), pack-reused 10059
Receiving objects: 100% (10071/10071), 6.31 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (5610/5610), done.
Checking connectivity... done.
bhanuc_1:~/workspace $ cd n2o/samples
bhanuc_1:~/workspace/n2o/samples (master) $ ./mad deps compile plan repl
==> dependency: "git://github.com/synrc/rest" tag: {tag,"2.9"}
==> dependency: "git://github.com/evanmiller/erlydtl" tag: {tag,"0.8.0"}
==> dependency: "git://github.com/synrc/nitro" tag: {tag,"master"}
==> dependency: "git://github.com/synrc/mad" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/sh" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/fs" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/active" tag: {tag,"1.9"}
==> dependency: "git://github.com/synrc/n2o" tag: {tag,"master"}
==> dependency: "git://github.com/sile/jsone.git" tag: {tag,"v0.3.3"}
==> dependency: "git://github.com/extend/cowboy" tag: {tag,"1.0.1"}
==> dependency: "git://github.com/ninenines/cowlib.git" tag: "1.0.0"
==> dependency: "git://github.com/ninenines/ranch.git" tag: "1.0.0"
==> dependency: "git://github.com/uwiger/gproc.git" tag: {tag,"0.3"}
==> dependency: "git://github.com/synrc/kvs" tag: {tag,"master"}
==> "rest"
Compiling /deps/rest/src/rest_app.erl
Compiling /deps/rest/src/rest.erl
Compiling /deps/rest/src/rest_sup.erl
Compiling /deps/rest/src/rest_cowboy.erl
Writing /deps/rest/ebin/rest.app
==> "erlydtl"
/usr/lib/erlang/lib/parsetools-2.0.10/include/yeccpre.hrl: no such file or directory
Compiling /deps/erlydtl/src/filter_lib/erlydtl_slice.erl
Line 12: error {include,lib,"eunit/include/eunit.hrl"} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 36: error {undefined,debugFmt,2} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 70: error {undefined,debugFmt,2} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 84: error {undefined,debugFmt,2} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 131: error {undefined,debugMsg,1} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 167: error {undefined,debugFmt,2} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 171: error {undefined,debugFmt,2} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 184: error {undefined,debugFmt,2} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 3: error {undefined_function,{slice_input_cases,7}} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 18: error {undefined_function,{parse_index,1}} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
Line 20: error {undefined_function,{slice_input_cases,7}} in "/deps/erlydtl/src/filter_lib/erlydtl_slice.erl"
ERROR: []
escript: exception error: no function clause matching 
                 lists:flatten({return,{return,[{error,[]}]}}) (lists.erl, line 601)
  in function  mad:main/1 (/Users/5HT/depot/synrc/mad/src/mad.erl, line 17)
  in call from escript:run/2 (escript.erl, line 747)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1 
  in call from init:start_em/1 


My erlang version is Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]
Eshell V5.10.4  
I am a beginner in erlang so any help would be highly appreciated.

**Comment by 5HT** [comment]
`erlydtl` doesn't support R16B03.
