### ISSUE TITLE
/erts-5.8.5/bin/beam.smp unknown flag -pc

### ISSUE THREAD

**Issue by bublik** [synrc/n2o#237]
Hello 
I am trying get started on my mac

[~/work/n2o/samples]$ ./mad deps compile plan repl
/usr/local/Cellar/erlang/R14B04/lib/erlang/erts-5.8.5/bin/beam.smp unknown flag -pc
Usage: beam.smp [flags] [ -- [init_args] ]

**Comment by fxmy** [comment]
search +pc Range in http://www.erlang.org/doc/man/erl.html
seems this flag is not supported at R14

**Comment by bublik** [comment]
thanx, updated to last erlang version
