### ISSUE TITLE
Kickstart bootstrap  - how i can get run  example

### ISSUE THREAD

**Issue by bublik** [synrc/n2o#238]
[~/work/n2o/samples]$ ./mad deps compile plan repl
Deps Params: []
==> dependency: "git://github.com/synrc/mad" tag: {tag,"master"}
==> dependency: "git://github.com/synrc/sh" tag: {tag,"1.4"}
==> dependency: "git://github.com/synrc/nitro" tag: {tag,"master"}
==> dependency: "git://github.com/synrc/n2o" tag: {tag,"master"}
==> dependency: "git://github.com/sile/jsone.git" tag: {tag,"v0.3.3"}
==> dependency: "git://github.com/extend/cowboy" tag: {tag,"1.0.1"}
==> dependency: "git://github.com/ninenines/cowlib.git" tag: "1.0.0"
==> dependency: "git://github.com/ninenines/ranch.git" tag: "1.0.0"
==> dependency: "git://github.com/uwiger/gproc.git" tag: {tag,"0.3"}
==> dependency: "git://github.com/evanmiller/erlydtl" tag: {tag,"0.8.0"}
==> dependency: "git://github.com/synrc/fs" tag: {tag,"1.4"}
==> dependency: "git://github.com/synrc/active" tag: {tag,"master"}
==> dependency: "git://github.com/synrc/rest" tag: {tag,"2.9"}
==> dependency: "git://github.com/synrc/kvs" tag: {tag,"2.8"}
Compile Params: []
==> "mad"
==> "sh"
==> "nitro"
==> "n2o"
==> "jsone"
==> "cowboy"
==> "cowlib"
==> "ranch"
==> "gproc"
==> "erlydtl"
==> "fs"
==> "active"
==> "rest"
==> "kvs"
==> "/Users/ruslanvoloshin/work/n2o/samples"
==> "/Users/ruslanvoloshin/work/n2o/samples/apps"
==> "/Users/ruslanvoloshin/work/n2o/samples/apps/review"
Plan Params: []
Ordered: [kernel,stdlib,fs,ranch,crypto,compiler,syntax_tools,mnesia,gproc,
          kvs,cowlib,cowboy,n2o,review,active,erlydtl,jsone,mad,nitro,rest,sh]
REPL Params: []
Configuration: [{n2o,[{port,8000},
                      {app,review},
                      {route,routes},
                      {mq,n2o_mq},
                      {formatter,bert},
                      {log_modules,config},
                      {log_level,config},
                      {log_backend,n2o_log},
                      {session,n2o_session},
                      {origin,<<"*">>},
                      {bridge,n2o_cowboy},
                      {pickler,n2o_pickle},
                      {erroring,n2o_error},
                      {event,pickle}]},
                {kvs,[{dba,store_mnesia},
                      {schema,[kvs_user,kvs_acl,kvs_feed,kvs_subscription]}]}]
Applications: [kernel,stdlib,fs,ranch,crypto,compiler,syntax_tools,mnesia,
               gproc,kvs,cowlib,cowboy,n2o,review,active,erlydtl,jsone,mad,
               nitro,rest,sh]
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.0  (abort with ^G)
1> Abort trap: 6

**Comment by 5HT** [comment]
Which OS?

**Comment by bublik** [comment]
OS X 10.9.5

**Comment by 5HT** [comment]
please do `./mad release mad` and share the tarball somehow

**Comment by 5HT** [comment]
Ah I see: 1> Abort trap: 6
You runned it twice. Check the ports with `netstat`

**Comment by 5HT** [comment]
Or check running `beam` instances `ps aux | grep beam`

**Comment by bublik** [comment]
[~/work/n2o/samples]$ netstat | grep 800
[~/work/n2o/samples]$ ps aux | grep beam
ruslanvoloshin  36920   0.0  0.0  2432784    600 s000  S+   12:21PM   0:00.00 grep beam

**Comment by bublik** [comment]
[~/work/n2o/samples]$ ./mad release mad
Release Params: ["mad"]
*WARNING* : Missing application sasl. Can not upgrade with this release
mad.boot: ok

**Comment by 5HT** [comment]
send me the tgz

**Comment by bublik** [comment]
509  git clone git://github.com/synrc/n2o
  510  cd n2o/samples
  511  ./mad deps compile plan repl 

  516  cd Downloads/
  518  tar -zxvf ./otp_src_18.0.tar.gz 
  519  cd otp_src_18.0
  521  ./configure 
  522  make
  523  make install

**Comment by 5HT** [comment]
Ha you are wrong, this is not right way to make Erlang.
In README clearly says that `synrc` supports only `brew` and `kerl` builded erlangs.

**Comment by bublik** [comment]
thanx will try replace

**Comment by 5HT** [comment]
You should install a lot of stuff before building Erlang from raw sources, if you're not experience Erlang builder better start from brew. Also we don't support any Linux packages (deb or rpm).

**Comment by 5HT** [comment]
If you will choose `kerl`, but we suggests you `brew`, you may use with `kerl` following configure options:

```
$ cat .kerlrc
KERL_CONFIGURE_OPTIONS="--enable-threads --enable-smp-support --enable-m64-build --without-javac --enable-kernel-poll --enable-hipe"
```

**Comment by bublik** [comment]
worked with brew instalation

**Comment by 5HT** [comment]
Thanks for feedback.
