### ISSUE TITLE
wf:flush/0 doesn't do what is supposed to do according to documentation

### ISSUE THREAD

**Issue by vjorjo** [synrc/n2o#257]
I wrote a simple example:
------------------------------------

```
-module(index).
-compile(export_all).
-include_lib("n2o/include/wf.hrl").
-include_lib("nitro/include/nitro.hrl").

main()    -> #dtl{file="index",app=sample,bindings=[{body,body()}]}.
body()    ->
	wf:info(?MODULE, "--- [ body() ] function was called", []),
	[
		#panel{id=test_panel, body = [
      #span{id=id1, body = "counter: "},
      #span{id = test_counter, body = "0"},
      #br{},
      #button{id=test_up, body="up", postback=up, source=[]}
    ]}
	].

counter_loop(init) ->
	wf:reg(counter), put(c1, 0),
	wf:info(?MODULE, "P: ~p, M: ~p", [self(), "counter init"]);
counter_loop(up) ->
	C = get(c1)+1,
	put(c1, C),
	wf:info(?MODULE, "P: ~p, Counter: ~p", [self(), C]),
	wf:update(test_counter,
		#span{id = test_counter, body = "hello counter, move your ass!"} ),
	wf:flush().

event(init) ->
	wf:info(?MODULE,"event(init) called",[]),
	wf:async("counter", fun counter_loop/1);
event(up) ->
	wf:send(counter, up);
event(Event) ->
	wf:info(?MODULE,"--- Unknown Event: ~p~n",[Event]).
```
and when I press the button "up" the #span text remains stuck to "0", while in the log I see the counter incrementing. 
It seems that "wf:flush/0" doesn't do its duty described in your book.

**Comment by 5HT** [comment]
Please read github markdown documentation before posting code snippets.
Also Github Issues is for N2O developers, not for user questions.
Please refer to README about the right order of using N2O resources.

**Comment by 5HT** [comment]
![screen shot 2015-12-06 at 9 57 38 pm](https://cloud.githubusercontent.com/assets/144776/11615248/7e277444-9c64-11e5-8980-df3a9f844c99.png)
Your example works perfectly: 

```Erlang
wf:update(test_counter,
        #span{id = test_counter, body = wf:f("hello ~p, move your ass!",[C])} ),
```

**Comment by vjorjo** [comment]
The fact that you 've put a "flattening" function that includes the value of the counter in my original list (a simple string), doesn't help at all, as it was expected.

Maybe, you misunderstood the bug:

wf:update/2 function works without problem when it is located in fun event/1.
But when it is in an async process registered with fun wf:async/2 as is the case in my code snippet where wf:update/2 is inside async process (a gen_server instance as the docs  claim) then it has no effects, despite calling wf:flush/0 which is said in the book (page 46, 7.4 "Async Processes wf:async and wf:flush") "should be called to redirect all updates and wire actions back to the page process from its async counterpart".

If it worked in your example, then you should have put the wf:update/2 function in an event/1 function. Because I tried my code in a windows and an ubuntu machine and I always get this:

counter:0

while I expected this:

counter:hello counter, move your ass!

As for not having the right to issue any issues the I encounter upon, I would like to say that I'm a developer too but I'm not working in N2O project. Did you mean that I have to get involved with N2O project in order to be allowed to issue any issues?

**Comment by vjorjo** [comment]
I tried version 2.11 of N2O and it doesn't have this issue.
For some mysterious reason I had version 2.9 which had this issue.

I apologize for this.
Where should I ask for help if I have any more issues?
