### ISSUE TITLE
GNU/Linux: core dump when another process owns the port

### ISSUE THREAD

**Issue by roobie** [synrc/n2o#258]
I am not sure whether this is a bug or a feature, since "let it crash" and all that. I just wanted to let you know that starting the sample project via `./mad repl` using the default port `8000` will crash with a core dump if another system process is running that is listening on the same port.

Checking the port for being free and tell the user if it's not is an alternative approach. 

my system info:
`Linux 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`

**Comment by m-2k** [comment]
Just change port in `sys.config` and keep calm.
