### ISSUE TITLE
"mad repl" freezes the input to console on Cygwin in Windows 7

### ISSUE THREAD

**Issue by carlosedp** [synrc/n2o#259]
When I run ./mad repl, my application starts perfectly but I cannot use the console (prints messages but no input).

To exit I need to Ctrl+C but the "erl" process kept running.

Probably the solution used on rebar3 would fix this problem in mad: 
Issue: https://github.com/rebar/rebar3/issues/563
Fix: https://github.com/rebar/rebar3/issues/995

**Comment by 5HT** [comment]
We don't support cygwin.
