### ISSUE TITLE
install on deb 7 failed

### ISSUE THREAD

**Issue by xoid** [synrc/n2o#261]
debian 7 last :
root@deb1:~/n2o/samples# ./mad deps compile plan repl
/usr/lib/erlang/erts-5.9.1/bin/beam unknown flag -pc

What is minimal requrements?

Cloud9 install failed too:
==> "active"
==> "n2o"
==> "jsone"
Compiling /deps/jsone/src/jsone.erl
Line 69: error {undefined_type,{map,0}} in "/deps/jsone/src/jsone.erl"
ERROR: []
escript: exception error: no function clause matching 
                 lists:flatten({return,{return,[{error,[]}]}}) (lists.erl, line 601)
  in function  mad:main/1 (/Users/5HT/depot/synrc/mad/src/mad.erl, line 17)
  in call from escript:run/2 (escript.erl, line 747)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1 
  in call from init:start_em/1

**Comment by 5HT** [comment]
You need Erlang version with maps. Also we don't support Debian packages.
