### ISSUE TITLE
n2o_static don't serve files consistenly

### ISSUE THREAD

**Issue by seb3s** [synrc/n2o#280]
Hi, n2o_static has a strange behaviour as it serves some files and is missing others.
I've replaced it by cowboy_static on my machine and all files get correctly served.

**Comment by 5HT** [comment]
Could you provide more details on this?

**Comment by seb3s** [comment]
Hi,
I've tried to reproduce it quickly by switching back to n2o_static as I was using cowboy_static for a while but was not able to do it.
So it's maybe a cache issue somewhere. I don't now what the n2o_static really does on top of cowboy_static ?
Cheers,
Sebastien.

**Comment by 5HT** [comment]
`n2o_static` is `cowboy_static` replacement when you need pack web site with full assets CSS/JS/HTML in `escript`-ize Erlang bundle. So when it runs you need to unpack the zip in ETS and provide file reading interface for router module.

In terms of underlying API you can see `mad_repl:load_file` wrapped around `file:read_file`. It is pretty simple only 70 LOC, you can read it here: https://github.com/synrc/n2o/blob/master/src/endpoints/cowboy/n2o_static.erl

I'm closing this issue as nonreproducible.
