### ISSUE TITLE
JavaScript Events over WebSocket issue

### ISSUE THREAD

**Issue by hamdijmii1992** [synrc/n2o#286]
Based on the  avaScript Events over WebSocket section in n2O book, i tried to made a test, the test description is as following:
I my index.erl I created an even that will accept the websocket call and do dome job:
my page header is as following:

`-module(index).
-compile(export_all).
-include_lib("kvs/include/entry.hrl").
-include_lib("nitro/include/nitro.hrl").
-include_lib("n2o/include/wf.hrl").`

and  this is my event handler:
 `event({client,{phone_auth,Phone}}) ->
 wf:info(?MODULE, "Phone: ~p~n",[Phone]).`

In the event I added a log function to test if the event is well triggered or not.

Now this is my websocket  request:
` var ws = new WebSocket("ws://192.168.1.19:8000/ws");
				
               ws.onopen = function()
               {
                  // Web Socket is connected, send data using send()
                 alert("Message to send");
                  ws.send(enc(tuple(atom('client'),
                  tuple(atom('phone_auth'),bin("+38054566267")))));
                  alert("Message is sent...");
               };`

I would like to know if I missing some think because When I invoke the websocket call my n2O app don't trigger the event handler.

**Comment by 5HT** [comment]
You shouldn't use `new WebSocket` directly. Instead you should use `new Bullet` as N2O does in 
https://github.com/synrc/n2o/blob/master/priv/n2o.js#L13

**Comment by hamdijmii1992** [comment]
Please, Can you tell me how can I perform n2O and PING/PONG protocol handshake before sending requests ?

**Comment by 5HT** [comment]
Actually you don't need to do that unless you wring your own JavaScript N2O client.
If you regular N2O user you should do exactly what in n2o/samples:

```
 <script>var transition = {pid: '', host: 'localhost', port:'8000'};</script>
        <script src='/n2o/protocols/bert.js'></script>
        <script src='/n2o/protocols/binary.js'></script>
        <script src='/n2o/protocols/client.js'></script>
        <script src='/n2o/protocols/nitrogen.js'></script>
        <script src='/n2o/bullet.js'></script>
        <script src='/n2o/xhr.js'></script>
        <script src='/n2o/utf8.js'></script>
        <script src='/n2o/template.js'></script>
        <script src='/n2o/n2o.js'></script>
        <script src='/n2o/validation.js'></script>
        <script src='/n2o/ftp.js'></script>
        <script>protos = [$client,$bert]; N2O_start();</script>
```

**Comment by 5HT** [comment]
```
function N2O_start() {
    ws = new bullet(protocol + host + (port==""?"":":"+port) + "/ws" + querystring);
    ws.onmessage = function (evt) { // formatters loop
    for (var i=0;i<protos.length;i++) { p = protos[i]; if (p.on(evt, p.do).status == "ok") return; } };
    ws.onopen = function() { if (!active) { console.log('Connect'); ws.send('N2O,'+transition.pid); active=true; } };
```

if you need custom OnMessage you should read how N2O onmessage implemented.
