### ISSUE TITLE
mad deps compile raises error

### ISSUE THREAD

**Issue by imgrey** [synrc/n2o#290]
Erlang R16B02

ERROR: []
escript: exception error: no function clause matching 
                 lists:flatten({return,{return,[{error,[]}]}}) (lists.erl, line 601)
  in function  mad:main/1 (/Users/5HT/depot/synrc/mad/src/mad.erl, line 17)
  in call from escript:run/2 (escript.erl, line 747)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_it/1 
  in call from init:start_em/1

**Comment by 5HT** [comment]
R16 is not supported.
