### ISSUE TITLE
Force redirection to login page after a few time of connexion

### ISSUE THREAD

**Issue by hamdijmii1992** [synrc/n2o#292]
Always, I was redirected to login page after few time of connection (5 -> 10 min).
I think that's an issue in my n2O configuration. 
When can I modify such parameter ?

**Comment by iamstarkov** [comment]
i dont think its a bug or feature request, thus i would suggest to close it /cc @5HT. 

But anyway if its help request, then @hamdijmii1992, can i ask you to create minimal re-producable github repo and link it here? without source code its hard to investigate and makes no sense to guess

**Comment by hamdijmii1992** [comment]
I forgot to delete a code snippet that cause this redirection
