### ISSUE TITLE
include different user.hrl cause rest api sample users.erl crash

### ISSUE THREAD

**Issue by slepher** [synrc/n2o#298]
just clonse n2o and run sample application use mad

curl -i localhost:8000/rest/users return 500 internal error

https://github.com/synrc/n2o/blob/master/samples/apps/review/src/users.erl
https://github.com/synrc/n2o/blob/master/samples/apps/review/src/review.erl

different user record used in users.erl and review.erl cause 

and while crashed, the n2o console does not populate anyting
I have to use dbg to trace where the crash happens.

> 1> dbg:tracer().
{ok,<0.607.0>}
2> dbg:tpl(rest_cowboy, to_json, cx).
{ok,[{matched,nonode@nohost,1},{saved,cx}]}
3> dbg:p(all, [c]).
{ok,[{matched,nonode@nohost,224}]}
4> (<0.612.0>) call rest_cowboy:to_json({http_req,#Port<0.51225>,ranch_tcp,keepalive,<0.612.0>,<<"GET">>,'HTTP/1.1',
          {{127,0,0,1},55207},
          <<"localhost">>,undefined,8000,<<"/rest/users">>,undefined,<<>>,
          undefined,
          [{resource,<<"users">>}],
          [{<<"host">>,<<"localhost:8000">>},
           {<<"connection">>,<<"keep-alive">>},
           {<<"cache-control">>,<<"max-age=0">>},
           {<<"upgrade-insecure-requests">>,<<"1">>},
           {<<"user-agent">>,
            <<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36">>},
           {<<"accept">>,
            <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8">>},
           {<<"accept-encoding">>,<<"gzip, deflate, br">>},
           {<<"accept-language">>,<<"zh-CN,zh;q=0.8">>},
           {<<"cookie">>,<<"site-sid=55b9f415a664f96dfff3e9d7b7bcb13d">>}],
          [{<<"if-modified-since">>,undefined},
           {<<"if-none-match">>,undefined},
           {<<"if-unmodified-since">>,undefined},
           {<<"if-match">>,undefined},
           {<<"accept">>,
            [{{<<"text">>,<<"html">>,[]},1000,[]},
             {{<<"application">>,<<"xhtml+xml">>,[]},1000,[]},
             {{<<"application">>,<<"xml">>,[]},900,[]},
             {{<<"image">>,<<"webp">>,[]},1000,[]},
             {{<<"image">>,<<"apng">>,[]},1000,[]},
             {{<<"*">>,<<"*">>,[]},800,[]}]},
           {<<"connection">>,[<<"keep-alive">>]}],
          undefined,
          [{media_type,{<<"application">>,<<"json">>,[]}},{charset,undefined}],
          waiting,<<>>,undefined,false,waiting,
          [{<<"content-type">>,[<<"application">>,<<"/">>,<<"json">>,<<>>]},
           {<<"Access-Control-Allow-Origin">>,<<"*">>}],
          <<>>,undefined},{st,users,undefined}) ({cowboy_rest,call,3})
(<0.612.0>) exception_from {rest_cowboy,to_json,2} {error,function_clause}

revision used
> git show
> commit c3ce1be2d0632795377d591b5a40f6a08622d6ff (HEAD -> master, origin/master, origin/HEAD)

erlang version

> brew info erlang
> erlang: stable 20.0.4 (bottled), HEAD

**Comment by 5HT** [comment]
Thanks for reporting.

**Comment by 5HT** [comment]
$ curl -i -X GET 127.0.0.1:8000/rest/users
HTTP/1.1 200 OK
connection: keep-alive
server: Cowboy
date: Mon, 11 Sep 2017 13:12:46 GMT
content-length: 854
Access-Control-Allow-Origin: *
content-type: application/json

{"users":[{"id":"roman","container":"feed","feed_id":[],"prev":[],"next":[],"feeds":[],"email":"roman@github.com","username":[],"password":[],"display_name":[],"register_date":[],"tokens":[],"images":[],"names":[],"surnames":[],"birth":[],"sex":[],"date":[],"status":[],"zone":[],"type":[]},{"id":"doxtop","container":"feed","feed_id":[],"prev":[],"next":[],"feeds":[],"email":"doxtop@synrc.com","username":[],"password":[],"display_name":[],"register_date":[],"tokens":[],"images":[],"names":[],"surnames":[],"birth":[],"sex":[],"date":[],"status":[],"zone":[],"type":[]},{"id":"maxim","container":"feed","feed_id":[],"prev":[],"next":[],"feeds":[],"email":"maxim@synrc.com","username":[],"password":[],"display_name":[],"register_date":[],"tokens":[],"images":[],"names":[],"surnames":[],"birth":[],"sex":[],"date":[],"status":[],"zone":[],"type":[]}]}
