### ISSUE TITLE
How can I get a return value from an N2O event ?

### ISSUE THREAD

**Issue by hamdijmii1992** [synrc/n2o#299]
I called an N2O event from my javascript client, then I want that the N2O event renders a json object to my client.
Actually, I have an event as follows:

```
event({client,{refresh_event,Data}}) ->
        %connect to a database and get a document 
	 [Doc];
```

I am able to call my event correctly, but in my onmessage callback I didn't get any thing useful, I always get an empty object although my Doc object is not empty.

My onmessage callback is as follows:

```
ws.onmessage = function onMessage(evt) { 
    if((evt.data != "PONG")){
     console.log(utf8_dec(evt.data));       
   }
  };  
```

I think that I missed something, can I have a hook to solve my issue please ?

**Comment by 5HT** [comment]
If you use your own message loop then everything is up to you.
In n2o we have following schema:

1. implement you own handler (there is no handler for `server` messages, only for `bin`
```
var $bin = {}; $bin.on = function onbin(r, cb) { if (is(r,2,'bin')) {
    if (typeof cb == 'function') cb(r); return { status: "ok" }; } else return { status: '' }; }
```
Include you proto handler:
```
 $bert.protos = [$io,$bin,$file];
```
use it on server side:
```
event(#bin{data=Data}) ->
    wf:info(?MODULE,"Binary Delivered ~p~n",[Data]),
    #bin{data = "SERVER"};
```

**Comment by hamdijmii1992** [comment]
Sorry I use the standard N2o message loop, I sent my message as follows:

```
 setTimeout(function () { ws.send(enc(tuple(atom('client'),
                  tuple(atom('refresh_event'),bin("hello")))));		  
				  }, 1000);
```

How can I receive in the onmessage  callback a valid json data from N2o page ?

**Comment by 5HT** [comment]
`BIN` stands for binary. It is not intended to use JSON in Binary prototocol.
Please read about protocols http://synrc.com/apps/n2o/doc/web/protocols.htm
for JSON traffic you need just to put 
```
 {n2o, [{port,8000},
            {formatter,bert},
````
but anyway you will receive:
```
 {"t":104,"v":[{"t":100,"v":"bin"},
                       {"t":107,"v":"SERVER v1"}]}
```
This is not JSON you are expected. To use real JSON you need to use synrc/rest or synrc/bert applications.

**Comment by 5HT** [comment]
`BIN` stands for binary. It is not intended to use JSON in Binary prototocol.
Please read about protocols http://synrc.com/apps/n2o/doc/web/protocols.htm
for JSON traffic you need just to put 
```
 {n2o, [{port,8000},
            {formatter,bert},
````
but anyway you will receive:
```
{"t":104,"v":[{"t":100,"v":"bin"},
                    {"t":107,"v":"SERVER v1"}]}
```

This is not JSON you are expected. Isn't it? To use what you really want you need not `n2o`, but [synrc/bert](http://github.com/synrc/bert) or [synrc/rest](http://github.com/synrc/rest) apps.
