### ISSUE TITLE
no function clause matching lists:flatten                           

### ISSUE THREAD

**Issue by 7stud** [synrc/n2o#310]
A few minutes ago, I cloned N20 from git:

`git clone git://github.com/synrc/n2o`

Then, I did:

`~/n2o/samples$ ./mad deps compile plan repl`

And in the output scrolling down my terminal window, I saw

> ERROR: "/Users/7stud/n2o/samples/apps/review"
> escript: exception error: no function clause matching lists:flatten({return,
>                                                             {return,
>                                                              [{error,
>                                                                "/Users/7stud/n2o

I installed `erlang 20.3` with the `asdf` version manager:

```
~/n2o/samples$ which erl
/Users/7stud/.asdf/shims/erl

~/n2o/samples$ erl
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.3  (abort with ^G)
1> 

```

**Comment by 5HT** [comment]
we don't support Erlang installed from package managers.
