### ISSUE TITLE
Fails on basic setup

### ISSUE THREAD

**Issue by etxemag75** [synrc/n2o#326]
When trying to get into N2O (from being very used to nitrogenproject), cloning and compiling it fails (on Mac) and it is not so obvious what's expected:

https://synrc.com/apps/n2o/doc/web/setup.htm

```
git clone git://github.com/synrc/n2o
cd n2o/samples
./mad deps compile plan repl
```

1) n2o/samples does not exist
2) the mad dependency is not meantioned
3) Just doing **make** on n2o does not work either due to lack of Makefile, however **rebar compile** works

**Comment by 5HT** [comment]
The official page is: htps://ws.n2o.space, the documentation site is https://n2o.dev

<img width="491" alt="Screen Shot 2019-05-13 at 1 57 48 PM" src="https://user-images.githubusercontent.com/144776/57616591-344ce480-7587-11e9-9913-3d257405d8b0.png">
