### ISSUE TITLE
N2O to support latest Cowboy 2.x

### ISSUE THREAD

**Issue by etxemag75** [synrc/n2o#327]
It seems N2O is not adapted to Cowboy 2.x and still using Cowboy 1.0

**Comment by 5HT** [comment]
No it's already 2.5 by default in all samples. In N2O itself there is no switch by N2O provide support for both 1.x and 2.5

**Comment by etxemag75** [comment]
But n2o_cowboy.erl is a HTTP Cowboy backend ({ok, Req, #state{}}) and n2o_cowboy2.erl is a WS Cowboy backend because the latter in init/2 do {cowboy_websocket, Req, Req}.

So if you want to serve nitrogen style webpages from server, like you mention in your book as chat.erl, how do you intend to make it work?

You need to do in cowboy_router:compile include {’_’,                   n2o_cowboy2,  []}

But there is no callback to the erlang module that should render the html page.

**Comment by 5HT** [comment]
Trust me :-)

**Comment by etxemag75** [comment]
Thx for your super quick responses:)

The example you refer to is a simple web socket app, you serve static html that opens up a web socket connection to server, which then allows it to be modified afaik.

What I am still trying to do (porting my nitrogen project app to n2o) is to serve the html the nitrogen way as you do it in your book chart.erl

<img width="950" alt="Screenshot 2019-05-17 at 14 12 53" src="https://user-images.githubusercontent.com/8653247/57927307-e6e5b580-78ad-11e9-9c04-bfb98be3ce36.png">

**Comment by 5HT** [comment]
This sample is historical and outdated. N2O BOOK is outdated. Please use https://n2o.dev
Official samples in README.md of N2O, namely: https://sample.n2o.space (WS), https://review.n2o.space (MQTT).

**Comment by 5HT** [comment]
BUT. If you REALLY need `n2o_document` I can promote this module in the next release. Just ensure me you can't live without in-request rendering and want `n2o_document` from 4.4 back in master.
