### ISSUE TITLE
from or form in record #cx ?

### ISSUE THREAD

**Issue by mihawk** [synrc/n2o#343]
from a previous version of #cx record you had a field call form 
in the new version you have new field call from, 
is it a typo ?

**Comment by 5HT** [comment]
In simple, No. The long answer is that form was indented to hold POST FORM, while from is for sender. These are similar by coincedence and have no any connection.

**Comment by mihawk** [comment]
ok thx, then where do you hold POST FORM  ?

**Comment by 5HT** [comment]
we don't as we're not POST/GET HTTP framework. But I'm sure you don't use all fields in #cx, so you man pick up any unused.

**Comment by mihawk** [comment]
ok thx i will check
