### ISSUE TITLE
Documentation completely sucks

### ISSUE THREAD

**Issue by prathmesh2308** [synrc/n2o#348]
git clone git://github.com/synrc/n2o
cd n2o/samples

cd: no such file or directory: n2o/samples

**Comment by 5HT** [comment]
I'm glad that you dislike our product! :-) Actually the documentation is in `man` folder.

**Comment by udanieli** [comment]
No doubt your product is tip-top, but the documentation indeed is outdated: the PDF book, [the website](https://synrc.com/apps/n2o/doc/web/setup.htm) and the README contains information about the `samples` directory which was removed in commit 9611ce7edcf991978fd82d37363d9500793189f0, a long time ago (Nov 16 2018).

**Comment by 5HT** [comment]
I'm ok that my documentation sucks and incomplete.
I'm just curiuous why are you're using archived sited stopped updating and copyrighted 2018 and not actual sites copyrighted 2020. What's wrong with you people?
![Capture](https://user-images.githubusercontent.com/144776/81506436-fbad2b80-92fe-11ea-952a-cae2e9a2d093.JPG)

**Comment by 5HT** [comment]
That's the official page and official instruction contained in readme and in distribution.

![Capture](https://user-images.githubusercontent.com/144776/81506544-bfc69600-92ff-11ea-8e68-7e7c12ef11f9.JPG)
