### ISSUE TITLE
There is no samples folder inside n2o

### ISSUE THREAD

**Issue by balaji-s** [synrc/n2o#358]
I am following the n2o setup, from this  link[https://synrc.com/apps/n2o/doc/web/setup.htm](url)

I have done the following steps:
$ git clone git://github.com/synrc/n2o
but when i did n2o/samples no such folder exists, can you update the tutorial 

and also running the following command 
$ mad get kvx
 results in Repository not found error
thanks

**Comment by 5HT** [comment]
![зображення](https://user-images.githubusercontent.com/144776/115155179-5f031a00-a087-11eb-8b55-63b70ba97bfb.png)

**Comment by 5HT** [comment]
Try

```
$ git clone https://github.com/synrc/sample.git
$ cd sample
$ rebar3 shell
```

And you'll get 

![зображення](https://user-images.githubusercontent.com/144776/115356562-70057580-a1c4-11eb-9374-6338666d751e.png)
